# Generated by Django 4.0.2 on 2022-02-21 09:18

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_alter_post_id_alter_post_published_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
