# Generated by Django 4.0.2 on 2022-02-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_alter_post_content_alter_post_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOfContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('title', models.CharField(max_length=40)),
                ('url', models.SlugField()),
            ],
            options={
                'ordering': ['-seq'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='toc',
            field=models.ManyToManyField(to='tutorial.TableOfContent'),
        ),
    ]
