# Generated by Django 4.0.2 on 2022-02-22 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_tableofcontent_alter_post_published_post_toc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='toc',
        ),
        migrations.AddField(
            model_name='post',
            name='stamp',
            field=models.ManyToManyField(related_name='stamps', to='tutorial.TableOfContent'),
        ),
        migrations.CreateModel(
            name='ContenGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.post')),
                ('toc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.tableofcontent')),
            ],
        ),
    ]
