# Generated by Django 4.0.2 on 2022-02-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_remove_post_toc_post_stamp_contengroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='stamp',
        ),
        migrations.DeleteModel(
            name='ContenGroup',
        ),
        migrations.DeleteModel(
            name='TableOfContent',
        ),
    ]
