# Generated by Django 4.0.2 on 2022-03-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_remove_post_stamp_delete_contengroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
